SirCoPOS.Web/Areas/Admin/Models/Pago.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SirCoPOS.Web.Areas.Admin.Models
{
    public class Pago
    {
        public DateTime? Fecha { get; set; }
        public string Estatus { get; set; }
        public IEnumerable<PagoDetalle> Detalle { get; set; }        
        public Venta Venta { get; set; }
    }

    public class PagoDetalle
    {
        public int FormaPago { get; set; }
        public decimal? Importe { get; set; }
        public string Sucursal { get; set; }
        public string Folio { get; set; }
        public string Terminacion { get; set; }
        public string Transaccion { get; set; }
    }
}

SirCoPOS.Web/Models/Pago.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SirCoPOS.Web.Models
{
    public class Pago
    {
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }
        [DataType(DataType.Currency)]
        public decimal Subtotal { get; set; }
        [DataType(DataType.Currency)]
        public decimal Descuento { get; set; }
        [DataType(DataType.Currency)]
        public decimal Importe { get; set; }
    }
}

SirCoPOS.Web/Controllers/SolicitudesController.cs
using SirCoPOS.BusinessLogic;
using SirCoPOS.Common.Entities;
using SirCoPOS.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZXing.QrCode.Internal;

namespace SirCoPOS.Web.Controllers
{
    [Authorize]
    public class SolicitudesController : Controller
    {
        public ActionResult Credito(Guid id)
        {
            var ctx = new DataAccess.SirCoPOSDataContext();
            var cctx = new DataAccess.SirCoCreditoDataContext();
            var ctxc = new DataAccess.SirCoControlDataContext();

            var item = ctx.SolicitudesCreditoVales.Where(i => i.Id == id).SingleOrDefault();
            if (item == null)
                return HttpNotFound();

            var ditem = cctx.Distribuidores.Where(i => i.iddistrib == item.ValeCliente.iddistrib).Single();
            
            //var usado = ctx.PlanPagos.Where(i => i.vale == vale).Sum(i => i.saldo);
            //var disponible = Math.Min(item.limitevale.Value, item.disponible.Value) - usado;

            var model = new Models.Distribuidor
            {
                Id = ditem.iddistrib,
                Cuenta = ditem.distrib,
                Nombre = ditem.nombre,
                ApMaterno = ditem.appaterno,
                ApPaterno = ditem.apmaterno,
                Status = ditem.idestatus.Value,
                Electronica = ditem.solocalzado == 0,
                Plazos = ditem.idperiodicidad.Value,
                Promocion = ditem.promocion == 1,
                Disponible = ditem.disponible,
                Date = ditem.fum,
                Tipo = ditem.tipodistrib,
                LimiteVale = ditem.limitevale,
                LimiteCredito = ditem.limitecredito                
            };
            var q = cctx.Pagos.Where(i => i.distrib == ditem.distrib && i.status == "AP");
            var primero = q.OrderBy(i => i.fum)
                .FirstOrDefault();
            if (primero != null)
                model.PrimerPago = primero.fum;

            var ultimos = q.OrderByDescending(i => i.fum)
                .Select(i => new Models.Pago {
                    Fecha = i.fecha.Value, 
                    Descuento = i.descuento.Value,
                    Subtotal = i.subtotal.Value, 
                    Importe = i.importe.Value
                })
               .Take(10);
            ViewBag.ultimos = ultimos;

            var qd = cctx.PlanPagos.Where(i =>
                i.distrib == ditem.distrib
                && i.saldo > 0
                && i.status == "AP");
            var saldo = qd.Any() ?
                qd.Sum(i => i.saldo) : 0;
            ViewBag.saldodis = saldo;

            var cliente = cctx.Clientes.Where(i => i.idcliente == item.ValeCliente.idcliente).Single();
            var suc = ctxc.Sucursales.Where(i => i.idsucursal == cliente.idsucursal).Single();

            var qp = cctx.PlanPagos.Where(i => 
                i.cliente == cliente.cliente && i.succliente == suc.sucursal
                && i.saldo > 0
                && i.status == "AP");
            var saldodis = qp.Where(i => i.distrib == ditem.distrib).Any() ?
                qp.Where(i => i.distrib == ditem.distrib).Sum(i => i.saldo) : 0;
            ViewBag.saldocli = saldodis;

            var saldoot = qp.Where(i => i.distrib != ditem.distrib).Any() ?
                qp.Where(i => i.distrib != ditem.distrib).Sum(i => i.saldo) : 0;            
            ViewBag.saldoOtros = saldoot;            

            var credito = new Models.SolicitudCliente
            {
                Vale = item.vale, 
                ApMaterno = cliente.apmaterno, 
                ApPaterno = cliente.appaterno, 
                Electronica = item.electronica, 
                Id = cliente.idcliente, 
                Cliente = cliente.cliente, 
                Nombre = cliente.nombre, 
                MontoVale = item.ValeCliente.cantidad,
                Monto = item.monto, 
                Faltante = item.monto - item.ValeCliente.cantidad
            };
            ViewBag.credito = credito;

            var uid = this.User.GetUID();
            if(item.idusuarioAprobacion.HasValue)
                ViewBag.mia = uid == item.idusuarioAprobacion;
            ViewBag.completado = item.fechaAprobacion.HasValue;

            ViewBag.id = id;
            return View(model);
        }
        [HttpPost]
        public ActionResult Take(Guid id)
        {
            var proxy = CommonServiceLocator.ServiceLocator.Current.GetInstance<Common.ServiceContracts.ICreditoValeService>();
            var uid = this.User.GetUID();
            if (!uid.HasValue)
                throw new NotSupportedException();
            proxy.Update(id, uid.Value);
            return Json(new { success = true, txt = "hello world" });
        }

        [HttpPost]
        public ActionResult Reply(Guid id, decimal? monto, decimal? credito, bool? electronica, string res)
        {
            var proxy = CommonServiceLocator.ServiceLocator.Current.GetInstance<Common.ServiceContracts.ICreditoValeService>();
            var request = new ReplyCreditoRequest
            {
                Id = id
            };
            if (res == "aceptar")
            {
                request.Approved = true;
                request.LimiteCredito = credito;
                request.MontoVale = monto;
                request.Electronica = electronica;
            }
            if (res == "rechazar")
            {
                request.Approved = false;
            }
            
            proxy.Complete(request);
            return Json(new { success = true, txt = "replied: " + res });
        }
    }
}

SirCoPOS.Web/Views/Solicitudes/Credito.cshtml
@model SirCoPOS.Web.Models.Distribuidor
@{
    ViewBag.Title = "Credito";
}
@{ 
    var esmia = (bool?)ViewBag.mia;
    var completado = (bool?)ViewBag.completado;
    var credito = (SirCoPOS.Web.Models.SolicitudCliente)ViewBag.credito;
}
<h2>Credito</h2>

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Detalle</a></li>
        <li role="presentation"><a href="#credito" aria-controls="detalle" role="tab" data-toggle="tab">Credito</a></li>
        <li role="presentation"><a href="#saldos" aria-controls="saldos" role="tab" data-toggle="tab">Saldos</a></li>
        <li role="presentation"><a href="#pagos" aria-controls="pagos" role="tab" data-toggle="tab">Pagos</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="detalle">
            @Html.Partial("_Details", Model)
            <hr />
            Saldo Distribuidor: @(String.Format("{0:C}", ViewBag.saldodis))
        </div>
        <div role="tabpanel" class="tab-pane" id="credito">
            @Html.Partial("_Credito", credito)            
        </div>
        <div role="tabpanel" class="tab-pane" id="saldos">

            <fieldset>
                <legend>Cliente</legend>
                Saldo: @(String.Format("{0:c}", ViewBag.saldocli))
                <br />
                Saldo Otros: @(String.Format("{0:c}", ViewBag.saldoOtros))
                <br />
                Saldo Total: <b>@(String.Format("{0:c}", ViewBag.saldocli + ViewBag.saldoOtros))</b>
            </fieldset>


        </div>
        <div role="tabpanel" class="tab-pane" id="pagos">
            @Html.Partial("_Pagos", (object)ViewBag.ultimos)
        </div>
    </div>

    <hr />

    <div>

    </div>

</div>

@if (!(completado ?? false))
{
<div id="bind" style="display: none">
    <div data-bind="visible: revisar() == 0">
        <button data-bind="click: function () { doRevisar(true); }">revisar</button>
    </div>
    <span data-bind="text: revisar"></span>
    <div data-bind="visible: revisar() == 1">
        revisando
        <hr />
        @using (Ajax.BeginForm("Reply", "Solicitudes", routeValues: new { id = ViewBag.id },
    ajaxOptions: new AjaxOptions { OnSuccess = "replied" },
    htmlAttributes: new { id = "freply " }))
        {
            <text>Nuevo Limite Vale:</text>
            <input type="text" name="monto" value="@((int)credito.Monto)" />
            <br />
            <text>Nuevo Limite Distribuidor:</text>
            <input type="text" name="credito" value="@((int)Model.LimiteCredito)" />
            <br />
            <text>Electronica:</text>
            <input type="checkbox" name="electronica" value="true" checked="@(Model.Electronica)" />
            <br />
            <input type="submit" name="res" value="aceptar" />
            <input type="submit" name="res" value="rechazar" />
        }
    </div>
    <div data-bind="visible: revisar() == 100">
        complete
    </div>
    <div data-bind="visible: revisar() == -1">
        la solicitud ya esta siendo revisada por alguien mas.
    </div>
</div>
}
else { 
    @:complete
}

    @using (Ajax.BeginForm("Take", "Solicitudes", routeValues: new { id = ViewBag.id },
        ajaxOptions: new AjaxOptions { OnSuccess = "taken" },
        htmlAttributes: new { id = "ftake" }))
    {

    }

    @section scripts
{
    <script>
        function replied(data) {
            vm.revisar(100);
            alert(data.txt);
        }
        function taken(data) {
            alert(data.txt);
        }
        function viewMovel() {
            var self = this;
            this.revisar = ko.observable(0);
            this.monto = ko.observable();
            this.doRevisar = function () {
                $("#ftake").submit();
                self.revisar(1);
            };
            this.doAceptar = function () {
                alert('aceptar');
            };
        }
        var vm = new viewMovel();
        $(function () {            
            @if (esmia.HasValue) {
                if (esmia.Value)
                {
                    <text>vm.revisar(1);</text>
                }
                else
                {
                    <text>vm.revisar(-1);</text>
                }
            }
            $('#bind').show();
            ko.applyBindings(vm, $('#bind')[0]);            
        });
        </script>
    }

SirCoPOS.Web/Views/Solicitudes/_Credito.cshtml
@model SirCoPOS.Web.Models.SolicitudCliente

<div>
    <h4>SolicitudCliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApPaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApPaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApMaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoVale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoVale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Faltante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faltante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Electronica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Electronica)
        </dd>

    </dl>
</div>

SirCoPOS.Web/Views/Solicitudes/_Details.cshtml
@model SirCoPOS.Web.Models.Distribuidor

@{ 
    TimeSpan? tspp = null;
    if (Model.PrimerPago.HasValue)
    {
        tspp = DateTime.Now - Model.PrimerPago;
    }
    var ts = DateTime.Now - Model.Date;
}

@helper displayRelative(TimeSpan ts)
{
    if (ts.TotalDays > 365)
    {
        var years = ts.TotalDays / 365;
        var mod = ts.TotalDays % 365;
        @String.Format("{0} años", (int)years)
        if (mod > 30)
        {
            var months = mod / 30;
            @String.Format(" {0} meses", (int)months)
        }
        else if (mod > 1)
        {
            @String.Format(" {0} dias", (int)mod)
        }
    }
    else if (ts.TotalDays > 30)
    {
        var months = ts.TotalDays / 30;
        var mod = ts.TotalDays % 30;
        @String.Format("{0} meses", (int)months)
        if (mod > 1)
        {
            @String.Format(" {0} dias", (int)mod)
        }
    }
    else if (ts.TotalDays > 1)
    {
        @String.Format("{0} dias", (int)ts.TotalDays)
    }
    else
    {
        if (ts.TotalHours > 1)
        {
            @String.Format("{0} horas", (int)ts.TotalHours)
        }
        else
        {
            @String.Format("{0} minutos", (int)ts.TotalMinutes)
        }

    }
}

<div>
    <h4>Distribuidor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cuenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApPaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApPaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApMaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Electronica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Electronica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContraVale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContraVale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Promocion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Promocion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disponible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disponible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LimiteCredito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LimiteCredito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LimiteVale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LimiteVale)
        </dd>

        <dt>Disponible Vale</dt>
        <dd>
            @if (Model.Disponible > Model.LimiteVale)
            {
                @String.Format("{0:C}", Model.LimiteVale)
            }
            else
            {
                @String.Format("{0:C}", Model.Disponible)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plazos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plazos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
            (@(displayRelative(ts.Value)))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimerPago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimerPago)
            @if (tspp.HasValue)
            { 
                @:(@(displayRelative(tspp.Value)))
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
    </dl>
</div>

SirCoPOS.Web/Views/Solicitudes/_Pagos.cshtml
@model IEnumerable<SirCoPOS.Web.Models.Pago>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subtotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descuento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Importe)
        </th>        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subtotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descuento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Importe)
        </td>        
    </tr>
}

</table>