SirCoPOS.Web/Areas/Admin/Models/Fondo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SirCoPOS.Web.Areas.Admin.Models
{
    public class Fondo
    {
    }
}

SirCoPOS.Web/Areas/Admin/Controllers/FondosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SirCoPOS.Web.Areas.Admin.Controllers
{
    public class FondosController : Controller
    {
        // GET: Admin/Fondos
        public ActionResult Index(string sucursal, byte? numero)
        {
            var ctx = new DataAccess.SirCoPOSDataContext();
            if (numero.HasValue)
            {
                var q = ctx.Fondos.Where(i => i.CajaSucursal == sucursal && i.CajaNumero == numero)
                    .OrderByDescending(i => i.FechaApertura);
                return View(q);
            }
            else
            {
                var q = ctx.Fondos.Where(i => !i.FechaCierre.HasValue)
                        .OrderByDescending(i => i.FechaApertura);
                return View(q);
            }
        }
        public ActionResult FondoFormasPago(int id)
        {
            var ctx = new DataAccess.SirCoPOSDataContext();
            var fondo = ctx.Fondos.Where(i => i.Id == id).SingleOrDefault();
            if (fondo == null)
                return HttpNotFound();
            var model = fondo.FormasPago;
            return View(model);
        }
    }
}

SirCoPOS.Web/Areas/Admin/Views/Fondos/FondoFormasPago.cshtml
@model IEnumerable<SirCoPOS.DataAccess.SirCoPOS.FondoFormaPago>
@{
    ViewBag.Title = "FondoFormasPago";
}

<h2>FondoFormasPago</h2>

<table class="table">
    <thead>
        <tr>
            <th>FormaPaga</th>
            <th>Monto</th>
            <th>Cantidad</th>
            <th>Usuario</th>
            <th>Entrada</th>
            <th>Fecha</th>
            <th>Referencia</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        { 
        <tr>
            <td>@((SirCoPOS.Common.Constants.FormaPago)item.FormaPago)</td>
            <td>@String.Format("{0:C}", item.Monto)</td>
            <td>@Html.DisplayFor(modelItem => item.Cantidad)</td>
            <td>@Html.DisplayFor(modelItem => item.UsuarioId)</td>
            <td>@Html.DisplayFor(modelItem => item.Entrada)</td>

            <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
            <td>@Html.DisplayFor(modelItem => item.Referencia)</td>

        </tr>
        }
    </tbody>
</table>

SirCoPOS.Web/Areas/Admin/Views/Fondos/Index.cshtml
@model IEnumerable<SirCoPOS.DataAccess.SirCoPOS.Fondo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResponsableId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaApertura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuditorAperturaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaCierre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuditorCierreId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Disponible)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CajaSucursal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CajaNumero)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ResponsableId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaApertura)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AuditorAperturaId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaCierre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AuditorCierreId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Disponible)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CajaSucursal)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CajaNumero)
    </td>
    <td>
        @Html.ActionLink("Movimientos", "Index", "FondoMovimientos", new { id = item.Id }, htmlAttributes: null) |
        @Html.ActionLink("FormasPago", "FondoFormasPago", "Fondos", new { id = item.Id }, htmlAttributes: null) |
        @Html.ActionLink("Arqueos", "Index", "FondoArqueos", new { id = item.Id }, htmlAttributes: null)
    </td>
</tr>
}

</table>