SirCoPOS.Web/Areas/Admin/Models/Caja.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SirCoPOS.Web.Areas.Admin.Models
{
    public class Caja
    {
        public DataAccess.SirCoPOS.Caja Item { get; set; }
        public int? Fondo { get; set; }
        public int? Responsable { get; set; }
    }
}

SirCoPOS.Web/Areas/Admin/Controllers/CajasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SirCoPOS.Web.Areas.Admin.Controllers
{
    public class CajasController : Controller
    {
        // GET: Admin/Fondos
        public ActionResult Index()
        {
            var admin = new BusinessLogic.Admin();
            var ctx = new DataAccess.SirCoPOSDataContext();
            var ctxpv = new DataAccess.SirCoPVDataContext();
            var items = ctx.Cajas
                .OrderByDescending(i => i.Disponible)
                .ThenBy(i => i.Numero)
                .Select(i => new Models.Caja
                { 
                    Item = i
                }).ToArray();
            foreach (var item in items)
            {
                var fondo = ctx.Fondos.Where(i => i.CajaSucursal == item.Item.Sucursal && i.CajaNumero == item.Item.Numero
                    && !i.FechaCierre.HasValue).SingleOrDefault();
                item.Fondo = fondo?.Id;
                item.Responsable = fondo?.ResponsableId;
            }
            //foreach (var item in items.Where(i => i.Item.Tipo == Common.Constants.TipoFondo.Cajon))
            //{
            //    item.Ventas = admin.VentasEfectivo(item.Item.Sucursal, item.Item.Numero);                
            //}
            return View(items);
        }
        public ActionResult Detalle(string sucursal, byte? numero)
        {
            var ctx = new DataAccess.SirCoPOSDataContext();
            var item = ctx.Cajas.Where(i => i.Sucursal == sucursal && i.Numero == numero).SingleOrDefault();
            if (item == null)
                return HttpNotFound();
            return View(item);
        }
    }
}

SirCoPOS.Web/Areas/Admin/Views/Cajas/Detalle.cshtml
@model SirCoPOS.DataAccess.SirCoPOS.Caja
@{
    ViewBag.Title = "Detalle";
}

<h2>@String.Format("{0}-{1}", Model.Sucursal, Model.Numero)</h2>
<h4>@Model.Tipo</h4>
<hr />
Efectivo: @String.Format("{0:C}", Model.Disponible)
<hr />
<table class="table">
    <thead>
        <tr>
            <th>FormaPago</th>
            <th>Monto</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.FormasPago)
        {
            <tr>
                <td>@((SirCoPOS.Common.Constants.FormaPago)item.FormaPago)</td>
                <td>@String.Format("{0:C}", item.Monto)</td>
            </tr>
        }
    </tbody>
</table>

SirCoPOS.Web/Areas/Admin/Views/Cajas/Index.cshtml
@model IEnumerable<SirCoPOS.Web.Areas.Admin.Models.Caja>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Item.Sucursal)</th>
        <th>@Html.DisplayNameFor(model => model.Item.Numero)</th>
        <th>@Html.DisplayNameFor(model => model.Item.Tipo)</th>
        <th>
            @Html.DisplayNameFor(model => model.Item.Disponible)
        </th>
        <th>Fondo</th>
        <th>Responsable</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>@Html.DisplayFor(modelItem => item.Item.Sucursal)</td>
    <td>@Html.DisplayFor(modelItem => item.Item.Numero)</td>
    <td>@Html.DisplayFor(modelItem => item.Item.Tipo)</td>
    <td>@String.Format("{0:C}", item.Item.Disponible)</td>
    <td>@item.Fondo</td>
    <td>@item.Responsable</td>
    <td>
        @Html.ActionLink("Detalle", "Detalle", "Cajas", routeValues: new { sucursal = item.Item.Sucursal, numero = item.Item.Numero }, htmlAttributes: null) |
        @Html.ActionLink("Fondos", "Index", "Fondos", routeValues: new { sucursal = item.Item.Sucursal, numero = item.Item.Numero }, htmlAttributes: null)
    </td>
</tr>
}

</table>