SirCoPOS.Web/Areas/Admin/Models/Venta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SirCoPOS.Web.Areas.Admin.Models
{
    public class Venta
    {
        public string Sucursal { get; set; }
        public string Folio { get; set; }
        public DateTime? Fecha { get; set; }
        public IEnumerable<Producto> Detalle { get; set; }
        public string Estatus { get; set; }
        public Persona Cajero { get; set; }
        public Persona Vendedor { get; set; }
        public Pago Pago { get; set; }
        public IEnumerable<PlanPago> PlanPago { get; set; }
        public Persona Cliente { get; internal set; }
        public IEnumerable<ContraVale> ContraVales { get; set; }
        public IEnumerable<DevolucionVenta> Devoluciones { get; set; }
    }

}

SirCoPOS.Web/Areas/Admin/Controllers/VentasController.cs
using SirCoPOS.Web.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SirCoPOS.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class VentasController : Controller
    {
        // GET: Admin/Ventas
        public ActionResult Index(int? fondo)
        {
            var ctx = new DataAccess.SirCoPVDataContext();
            if (fondo.HasValue)
            {
                var ctxpos = new DataAccess.SirCoPOSDataContext();
                var f = ctxpos.Fondos.Where(i => i.Id == fondo).SingleOrDefault();
                if (f == null)
                    return HttpNotFound();
                var q = ctx.Ventas.Where(i => i.fum > f.FechaApertura 
                    && i.idcajero == f.ResponsableId
                    && i.sucursal == f.CajaSucursal);
                if (f.FechaCierre.HasValue)
                    q = q.Where(i => i.fum < f.FechaCierre);
                var res = q.OrderByDescending(i => i.fum);
                return View(q);
            }
            else
            {
                var date = DateTime.Today.AddDays(-15);                
                var q = ctx.Ventas.Where(i => i.fecha > date).OrderByDescending(i => i.fum).Take(50);
                return View(q);
            }            
        }
        private Models.Persona GetEmpleado(int? id)
        {
            var ctxn = new DataAccess.SirCoNominaDataContext();

            if (!id.HasValue)
                return null;

            var emp = ctxn.Empleados.Where(i => i.idempleado == id).SingleOrDefault();
            if (emp == null)
                return new Models.Persona { Id = id.Value };

            return new Models.Persona
            {
                Id = emp.idempleado, 
                Nombre = emp.nombre, 
                ApPaterno = emp.appaterno, 
                ApMaterno = emp.apmaterno
            };            
        }
        public ActionResult Detalle(string sucursal, string folio)
        {
            var ctx = new DataAccess.SirCoPVDataContext();
            var ctxc = new DataAccess.SirCoCreditoDataContext();
            var item = ctx.Ventas.Where(i => i.sucursal == sucursal && i.venta == folio).SingleOrDefault();
            if (item == null)
                return HttpNotFound();

            Persona cliente = null;
            if (item.idcliente.HasValue)
            {
                var cli = ctxc.Clientes.Where(i => i.idcliente == item.idcliente).SingleOrDefault();
                if (cli == null)
                    cliente = new Persona { Id = item.idcliente.Value };
                else
                {
                    cliente = new Persona
                    {
                        Id = cli.idcliente, 
                        Nombre = cli.nombre, 
                        ApPaterno = cli.appaterno, 
                        ApMaterno = cli.apmaterno
                    };
                }                
            }

            var model = new Models.Venta
            {
                Sucursal = item.sucursal,
                Folio = item.venta,
                Fecha = item.fum,
                Estatus = item.estatus,
                Cajero = this.GetEmpleado(item.idcajero),
                Vendedor = this.GetEmpleado(item.idvendedor),
                Cliente = cliente
            };
            var plist = new List<Models.Producto>();
            foreach (var i in item.Detalles)
            {
                if(i.idrazon.HasValue)
                    ctx.Entry(i).Reference(k => k.NotaRazon).Load();
                plist.Add(new Models.Producto
                {
                    Renglon = i.renglon,
                    Marca = i.marca,
                    Modelo = i.estilon,
                    Serie = i.serie,
                    Precio = i.precio,
                    Pago = i.precdesc,
                    Comments = i.descuentoespecialdesc,
                    Notas = i.notas,
                    NotaRazon = i.idrazon.HasValue ? i.NotaRazon.descripcion : null
                });
            }            
            model.Detalle = plist;

            var ctxi = new DataAccess.SirCoImgDataContext();
            foreach (var det in model.Detalle)
            {
                var q = ctxi.Imagenes.Where(i => i.Marca == det.Marca && i.Estilon == det.Modelo);
                det.HasImage = q.Any();
            }

            model.ContraVales = ctxc.ContraVales.Where(i => i.sucursal == item.sucursal && i.referenc == item.venta)
                .Select(i => new Models.ContraVale { Folio = i.cvale, Disponible = i.saldo, Importe = i.importe });

            model.Devoluciones = ctx.Devoluciones.Where(i => i.referencia == item.sucursal + item.venta)
                .Select(i => new Models.DevolucionVenta { 
                    Sucursal = i.sucursal,
                    Folio = i.devolvta,
                    Importe = i.disponible
                });

            model.Pago = new Models.Pago
            {
                Fecha = item.Pago.fum,
                Estatus = item.Pago.estatus
            };
            var pagos = new List<Models.PagoDetalle>();
            foreach (var i in item.Pago.Detalle)
            {
                var pd = new Models.PagoDetalle
                {
                    FormaPago = i.idformapago,
                    Importe = i.importe
                };
                if (pd.FormaPago == (int)Common.Constants.FormaPago.DV
                    && i.referencia != null)
                {
                    pd.Sucursal = i.referencia.Substring(0, 2);
                    pd.Folio = i.referencia.Substring(2);
                }
                else if ((pd.FormaPago == (int)Common.Constants.FormaPago.TC || pd.FormaPago == (int)Common.Constants.FormaPago.TD)
                    && i.terminacion != null)
                {
                    pd.Terminacion = i.terminacion;
                    pd.Transaccion = i.transaccion;
                } 
                else if (pd.FormaPago == (int)Common.Constants.FormaPago.VA)
                {
                    pd.Folio = i.vale;
                    var qpp = ctxc.PlanPagos.Where(k => k.sucursal == sucursal && k.nota == folio && k.vale == i.vale);
                    if (qpp.Any())
                    {
                        ViewBag.hasPlanPagos = true;
                        var list = new List<Models.PlanPago>();
                        model.PlanPago = list;
                        foreach (var pp in qpp)
                        {
                            //pd.Sucursal = pp.sucursal;
                            //pd.Folio = pp.vale;

                            list.Add(new Models.PlanPago
                            {
                                Vale = pp.vale,
                                Detalle = pp.Detalle.Select(k => new Models.PlanPagoDetalle
                                {
                                    Fecha = k.fechaaplicar,
                                    Importe = k.importe,
                                    Number = k.pago
                                })
                            });
                        }
                    }
                }
                pagos.Add(pd);
            }
            model.Pago.Detalle = pagos;

            return View(model);
        }
    }
}

SirCoPOS.Web/Controllers/ImagesController.cs
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZXing;
using ZXing.Common;
using ZXing.QrCode.Internal;
using ZXing.Rendering;

namespace SirCoPOS.Web.Controllers
{
    public class ImagesController : Controller
    {
        public ActionResult Producto(int? id, string marca, string modelo, int w = 100, int h = 100)
        {
            var ctx = new DataAccess.SirCoDataContext();
            var ctxi = new DataAccess.SirCoImgDataContext();

            if (id.HasValue)
            {
                var item = ctx.Articulos.Where(i => i.Id == id).SingleOrDefault();
                if (item == null)
                    return HttpNotFound();
                marca = item.Marca;
                modelo = item.Modelo;
            }
            else
            {
                if (modelo.Length < 7)
                    modelo = modelo.PadLeft(7);
            }
            //=============================================================================================================================================
            var img = ctxi.Imagenes.Where(i => i.Marca == marca && i.Estilon == modelo).SingleOrDefault();
            if (img == null || img.Foto == null)
                return HttpNotFound();

            var ms = new System.IO.MemoryStream();
            ImageResizer.ImageBuilder.Current.Build(img.Foto, ms,
                new ImageResizer.ResizeSettings()
                {
                    Mode = ImageResizer.FitMode.None,
                    Width = w,
                    Height = h,
                    Format = "png"
                });
            ms.Position = 0;

            return File(ms, "image/png", $"{marca}_{modelo.Replace(' ', '_')}.png");
        }
        public ActionResult Firma(int id, short num, int w = 100, int h = 100)
        {
            var ctx = new DataAccess.SirCoCreditoDataContext();

            var item = ctx.Distribuidores.Where(i => i.iddistrib == id).SingleOrDefault();
            if (item == null)
                return HttpNotFound();
            var img = ctx.DistribuidorFirmas.Where(i => i.distrib == item.distrib && i.numfirma == num).SingleOrDefault();
            if (img == null || img.firma == null)
                return HttpNotFound();

            var ms = new System.IO.MemoryStream();
            ImageResizer.ImageBuilder.Current.Build(img.firma, ms,
                new ImageResizer.ResizeSettings()
                {
                    Mode = ImageResizer.FitMode.None,
                    Width = w,
                    Height = h,
                    Format = "png"
                });
            ms.Position = 0;

            return File(ms, "image/png", $"{item.iddistrib}_{img.numfirma}.png");
        }

        public ActionResult Empleado(int id, int w = 100, int h = 100)
        {
            var ctx = new DataAccess.SirCoNominaDataContext();
            var img = ctx.EmpleadosImgs.Where(i => i.idempleado == id).SingleOrDefault();
            if (img == null || img.foto == null)
                return HttpNotFound();

            var ms = new System.IO.MemoryStream();
            ImageResizer.ImageBuilder.Current.Build(img.foto, ms,
                new ImageResizer.ResizeSettings()
                {
                    Mode = ImageResizer.FitMode.None,
                    Width = w,
                    Height = h,
                    Format = "png"
                });
            ms.Position = 0;

            return File(ms, "image/png", $"{id}.png");
        }
        public ActionResult Promocion(int id, int w = 200, int h = 200)
        {
            var ctx = new DataAccess.SirCoPVDataContext();
            var img = ctx.Promociones.Where(i => i.idpromocion == id).SingleOrDefault();
            if (img == null || img.imagen == null)
                return HttpNotFound();

            var ms = new System.IO.MemoryStream();
            ImageResizer.ImageBuilder.Current.Build(img.imagen, ms,
                new ImageResizer.ResizeSettings()
                {
                    Mode = ImageResizer.FitMode.None,
                    Width = w,
                    Height = h,
                    Format = "png"
                });
            ms.Position = 0;

            return File(ms, "image/png", $"{id}.png");
        }
        public ActionResult Cliente(int id, int w = 200, int h = 200)
        {
            var ctx = new DataAccess.SirCoCreditoDataContext();
            var img = ctx.Clientes.Where(i => i.idcliente == id).SingleOrDefault();
            if (img == null || img.foto == null)
                return HttpNotFound();

            var ms = new System.IO.MemoryStream();
            ImageResizer.ImageBuilder.Current.Build(img.foto, ms,
                new ImageResizer.ResizeSettings()
                {
                    Mode = ImageResizer.FitMode.None,
                    Width = w,
                    Height = h,
                    Format = "png"
                });
            ms.Position = 0;

            return File(ms, "image/png", $"{id}.png");
        }

        public ActionResult QrCode(string id, int w = 100, int h = 100)
        {
            var barcodeWriter = new ZXing.BarcodeWriter();
            var encodingOptions = new EncodingOptions { Width = w, Height = h, Margin = 0, PureBarcode = false };
            encodingOptions.Hints.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
            barcodeWriter.Renderer = new BitmapRenderer();
            barcodeWriter.Options = encodingOptions;
            barcodeWriter.Format = BarcodeFormat.QR_CODE;
            var bitmap = barcodeWriter.Write(id);

            var ms = new System.IO.MemoryStream();
            bitmap.Save(ms, ImageFormat.Png);
            ms.Position = 0;
            return File(ms, "image/png", $"{id}.png");
        }
        public ActionResult Code(string code)
        {
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(code, QRCodeGenerator.ECCLevel.Q);
            QRCoder.QRCode qrCode = new QRCoder.QRCode(qrCodeData);
            var qrCodeImage = qrCode.GetGraphic(4);
            var ms = new System.IO.MemoryStream();
            qrCodeImage.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
            ms.Position = 0;
            return File(ms, "image/png");
        }
        public ActionResult BarCode(string id, int w = 100, int h = 100)
        {
            var barcodeWriter = new ZXing.BarcodeWriter();
            var encodingOptions = new EncodingOptions { Width = w, Height = h, Margin = 0, PureBarcode = false };
            encodingOptions.Hints.Add(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
            barcodeWriter.Renderer = new BitmapRenderer();
            barcodeWriter.Options = encodingOptions;
            barcodeWriter.Format = BarcodeFormat.CODE_128;
            var bitmap = barcodeWriter.Write(id);

            var ms = new System.IO.MemoryStream();
            bitmap.Save(ms, ImageFormat.Png);
            ms.Position = 0;
            return File(ms, "image/png", $"{id}.png");
        }
    }
}

SirCoPOS.Web/Areas/Admin/Views/Ventas/Detalle.cshtml
@model SirCoPOS.Web.Areas.Admin.Models.Venta

@{
    ViewBag.Title = "Detalle";
}

@helper printPersona(SirCoPOS.Web.Areas.Admin.Models.Persona per)
{
if (per != null)
{ 
@String.Format("{0} - {1} {2} {3}", per.Id, per.Nombre, per.ApPaterno, per.ApMaterno)
}
} 

<h2>Detalle</h2>

<div>
    <h4>Venta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Sucursal</dt>
        <dd>@Model.Sucursal</dd>

        <dt>Folio</dt>
        <dd>@Model.Folio</dd>

        <dt>Fecha</dt>
        <dd>@Model.Fecha</dd>

        <dt>Estatus</dt>
        <dd>@Model.Estatus</dd>

        <dt>Cajero</dt>
        <dd>@printPersona(Model.Cajero)</dd>

        <dt>Vendedor</dt>
        <dd>@printPersona(Model.Vendedor)</dd>

        <dt>Cliente</dt>
        <dd>@printPersona(Model.Cliente)</dd>
    </dl>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Serie</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Precio</th>
                <th>Pago</th>
                <th>Descuento</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Detalle)
            {
            <tr>
                <td>@item.Serie</td>
                <td>@item.Marca</td>
                <td>@item.Modelo</td>
                <td>
                    @item.Precio.Value.ToString("c")
                    @if (item.NotaRazon != null)
                    {
                        if (item.Notas != null)
                        {
                            @String.Format("({0} - {1})", item.NotaRazon, item.Notas)
                        }
                        else
                        {
                            @String.Format("({0})", item.NotaRazon)
                        }
                    }
                </td>
                <td>@item.Pago.Value.ToString("c")</td>
                <td>@String.Format("{0:p}", item.DescuentoPorcentaje)</td>
                <td>@item.Comments</td>
                <td>
                    @if (item.HasImage)
                    {
                        <img src="@Url.Action("Producto", "Images", new { area = "", marca = item.Marca, modelo = item.Modelo, w = 100, h = 100 })" />
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
    <h4>Pago</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Fecha</dt>
        <dd>@Model.Pago.Fecha</dd>

        <dt>Estatus</dt>
        <dd>@Model.Pago.Estatus</dd>
    </dl>
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>TipoPago</th>
                <th>Importe</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Pago.Detalle)
            {
                <tr>
                    <td>@($"{item.FormaPago} - {(SirCoPOS.Common.Constants.FormaPago)item.FormaPago}")</td>
                    <td>@($"{item.Importe:c}")</td>
                    <td>
                        @if (item.FormaPago == (int)SirCoPOS.Common.Constants.FormaPago.DV && item.Folio != null)
                        {
                            <a href="@Url.Action("Detalle", "Devoluciones", new { sucursal = item.Sucursal, folio = item.Folio })">@($"{item.Sucursal}-{item.Folio}")</a>
                        }
                        @if ((item.FormaPago == (int)SirCoPOS.Common.Constants.FormaPago.TC || item.FormaPago == (int)SirCoPOS.Common.Constants.FormaPago.TD)
                            && item.Terminacion != null)
                        {
                            @($"Terminacion: {item.Terminacion}, Transaccion: {item.Transaccion}")
                        }
                        @if (item.FormaPago == (int)SirCoPOS.Common.Constants.FormaPago.VA && item.Folio != null)
                        {
                            @($"Vale: {item.Folio}")
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (Model.ContraVales.Any())
    {
        <h4>Contra Vales</h4>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Importe</th>
                    <th>Saldo</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cv in Model.ContraVales)
                {
                    <tr>
                        <td>@cv.Folio</td>
                        <td>@cv.Importe</td>
                        <td>@cv.Disponible</td>
                    </tr>
                }
            </tbody>
        </table>    
    }
    @if (ViewBag.hasPlanPagos ?? false)
    {
        foreach (var pp in Model.PlanPago)
        {
            <h4>Plan Pagos - @pp.Vale</h4>
            <hr />
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Fecha</th>
                        <th>Importe</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in pp.Detalle)
                    {
                        <tr>
                            <td>@item.Number</td>
                            <td>@item.Fecha.ToShortDateString()</td>
                            <td>@item.Importe.ToString("c")</td>
                        </tr>

                    }
                </tbody>
            </table>
        }
    }

<div>
    <h4>Devoluciones</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>Devolucion</th>
                <th>Disponible</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Devoluciones)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("Detalle", "Devoluciones", new { sucursal = item.Sucursal, folio = item.Folio })">@($"{item.Sucursal}-{item.Folio}")</a>
                    </td>
                    <td>@($"{item.Importe:c}")</td>
                </tr>
            }
        </tbody>
    </table>
</div>
</div>
<p>
    @Html.ActionLink("Back", "Index")
</p>

SirCoPOS.Web/Areas/Admin/Views/Ventas/Index.cshtml
@model IEnumerable<SirCoPOS.DataAccess.SirCoPV.Venta>
@{
    ViewBag.Title = "Ventas";
}

<h2>Ventas</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Sucursal</th>
            <th>Folio</th>
            <th>Fecha</th>
            <th>Estatus</th>
            <th>Cajero</th>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.sucursal</td>
            <td>@item.venta</td>
            <td>@item.fecha.Value.ToShortDateString()</td>
            <td>@item.estatus</td>
            <td>@item.idcajero</td>
            <td>@item.idvendedor</td>
            <td>@item.idcliente</td>
            <td><a href="@Url.Action("Detalle", new { sucursal = item.sucursal, folio = item.venta })">detalle</a></td>
        </tr>
        }
    </tbody>
</table>